name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet pack --configuration Release
    - name: Add private GitHub registry to NuGet
      run: |
        dotnet nuget add source --username Megghy --password ${{secrets.GHKEY}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Megghy/index.json"
    - name: Push generated package to GitHub registry
      run: |
        dotnet nuget push ./BiliAPI/bin/Release/*.nupkg -s "github" --skip-duplicate -n true
        dotnet nuget push ./BiliAPI/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -n true --skip-duplicate -k ${{secrets.NUGETKEY}}
